# Generated by Django 3.1.2 on 2020-11-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300)),
                ('Lname', models.CharField(max_length=300)),
                ('grade', models.IntegerField(max_length=12)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('fatherName', models.CharField(max_length=300)),
                ('mothersName', models.CharField(max_length=300)),
                ('studentNumber', models.IntegerField(max_length=20)),
                ('fathersNumber', models.IntegerField(max_length=20)),
                ('mothersNumber', models.IntegerField(max_length=20)),
                ('personalEmail', models.EmailField(max_length=254)),
                ('schoolEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
