# Generated by Django 3.1.2 on 2020-11-22 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_assignment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 8, 6, 19, 502636)),
        ),
    ]
